// Code generated by "perm_generator -file vendor/git.subiz.net/header/auth/auth.pb.go -type Permission"; DO NOT EDIT.

package perm

import "git.subiz.net/header/auth"

func CheckCreateAccount(cred *auth.Credential, accid string, agids ...string) error {
	p := "c"
	callerperm := cred.GetPerm().GetAccount()
	base := Base.GetAccount()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckReadAccount(cred *auth.Credential, accid string, agids ...string) error {
	p := "r"
	callerperm := cred.GetPerm().GetAccount()
	base := Base.GetAccount()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckUpdateAccount(cred *auth.Credential, accid string, agids ...string) error {
	p := "u"
	callerperm := cred.GetPerm().GetAccount()
	base := Base.GetAccount()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckDeleteAccount(cred *auth.Credential, accid string, agids ...string) error {
	p := "d"
	callerperm := cred.GetPerm().GetAccount()
	base := Base.GetAccount()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckCreateAgent(cred *auth.Credential, accid string, agids ...string) error {
	p := "c"
	callerperm := cred.GetPerm().GetAgent()
	base := Base.GetAgent()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckReadAgent(cred *auth.Credential, accid string, agids ...string) error {
	p := "r"
	callerperm := cred.GetPerm().GetAgent()
	base := Base.GetAgent()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckUpdateAgent(cred *auth.Credential, accid string, agids ...string) error {
	p := "u"
	callerperm := cred.GetPerm().GetAgent()
	base := Base.GetAgent()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckDeleteAgent(cred *auth.Credential, accid string, agids ...string) error {
	p := "d"
	callerperm := cred.GetPerm().GetAgent()
	base := Base.GetAgent()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckCreateAgentPassword(cred *auth.Credential, accid string, agids ...string) error {
	p := "c"
	callerperm := cred.GetPerm().GetAgentPassword()
	base := Base.GetAgentPassword()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckReadAgentPassword(cred *auth.Credential, accid string, agids ...string) error {
	p := "r"
	callerperm := cred.GetPerm().GetAgentPassword()
	base := Base.GetAgentPassword()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckUpdateAgentPassword(cred *auth.Credential, accid string, agids ...string) error {
	p := "u"
	callerperm := cred.GetPerm().GetAgentPassword()
	base := Base.GetAgentPassword()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckDeleteAgentPassword(cred *auth.Credential, accid string, agids ...string) error {
	p := "d"
	callerperm := cred.GetPerm().GetAgentPassword()
	base := Base.GetAgentPassword()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckCreatePermission(cred *auth.Credential, accid string, agids ...string) error {
	p := "c"
	callerperm := cred.GetPerm().GetPermission()
	base := Base.GetPermission()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckReadPermission(cred *auth.Credential, accid string, agids ...string) error {
	p := "r"
	callerperm := cred.GetPerm().GetPermission()
	base := Base.GetPermission()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckUpdatePermission(cred *auth.Credential, accid string, agids ...string) error {
	p := "u"
	callerperm := cred.GetPerm().GetPermission()
	base := Base.GetPermission()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckDeletePermission(cred *auth.Credential, accid string, agids ...string) error {
	p := "d"
	callerperm := cred.GetPerm().GetPermission()
	base := Base.GetPermission()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckCreateAgentGroup(cred *auth.Credential, accid string, agids ...string) error {
	p := "c"
	callerperm := cred.GetPerm().GetAgentGroup()
	base := Base.GetAgentGroup()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckReadAgentGroup(cred *auth.Credential, accid string, agids ...string) error {
	p := "r"
	callerperm := cred.GetPerm().GetAgentGroup()
	base := Base.GetAgentGroup()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckUpdateAgentGroup(cred *auth.Credential, accid string, agids ...string) error {
	p := "u"
	callerperm := cred.GetPerm().GetAgentGroup()
	base := Base.GetAgentGroup()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckDeleteAgentGroup(cred *auth.Credential, accid string, agids ...string) error {
	p := "d"
	callerperm := cred.GetPerm().GetAgentGroup()
	base := Base.GetAgentGroup()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckCreateSegmentation(cred *auth.Credential, accid string, agids ...string) error {
	p := "c"
	callerperm := cred.GetPerm().GetSegmentation()
	base := Base.GetSegmentation()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckReadSegmentation(cred *auth.Credential, accid string, agids ...string) error {
	p := "r"
	callerperm := cred.GetPerm().GetSegmentation()
	base := Base.GetSegmentation()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckUpdateSegmentation(cred *auth.Credential, accid string, agids ...string) error {
	p := "u"
	callerperm := cred.GetPerm().GetSegmentation()
	base := Base.GetSegmentation()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckDeleteSegmentation(cred *auth.Credential, accid string, agids ...string) error {
	p := "d"
	callerperm := cred.GetPerm().GetSegmentation()
	base := Base.GetSegmentation()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckCreateClient(cred *auth.Credential, accid string, agids ...string) error {
	p := "c"
	callerperm := cred.GetPerm().GetClient()
	base := Base.GetClient()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckReadClient(cred *auth.Credential, accid string, agids ...string) error {
	p := "r"
	callerperm := cred.GetPerm().GetClient()
	base := Base.GetClient()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckUpdateClient(cred *auth.Credential, accid string, agids ...string) error {
	p := "u"
	callerperm := cred.GetPerm().GetClient()
	base := Base.GetClient()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckDeleteClient(cred *auth.Credential, accid string, agids ...string) error {
	p := "d"
	callerperm := cred.GetPerm().GetClient()
	base := Base.GetClient()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckCreateRule(cred *auth.Credential, accid string, agids ...string) error {
	p := "c"
	callerperm := cred.GetPerm().GetRule()
	base := Base.GetRule()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckReadRule(cred *auth.Credential, accid string, agids ...string) error {
	p := "r"
	callerperm := cred.GetPerm().GetRule()
	base := Base.GetRule()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckUpdateRule(cred *auth.Credential, accid string, agids ...string) error {
	p := "u"
	callerperm := cred.GetPerm().GetRule()
	base := Base.GetRule()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckDeleteRule(cred *auth.Credential, accid string, agids ...string) error {
	p := "d"
	callerperm := cred.GetPerm().GetRule()
	base := Base.GetRule()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckCreateConversation(cred *auth.Credential, accid string, agids ...string) error {
	p := "c"
	callerperm := cred.GetPerm().GetConversation()
	base := Base.GetConversation()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckReadConversation(cred *auth.Credential, accid string, agids ...string) error {
	p := "r"
	callerperm := cred.GetPerm().GetConversation()
	base := Base.GetConversation()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckUpdateConversation(cred *auth.Credential, accid string, agids ...string) error {
	p := "u"
	callerperm := cred.GetPerm().GetConversation()
	base := Base.GetConversation()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckDeleteConversation(cred *auth.Credential, accid string, agids ...string) error {
	p := "d"
	callerperm := cred.GetPerm().GetConversation()
	base := Base.GetConversation()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckCreateIntegration(cred *auth.Credential, accid string, agids ...string) error {
	p := "c"
	callerperm := cred.GetPerm().GetIntegration()
	base := Base.GetIntegration()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckReadIntegration(cred *auth.Credential, accid string, agids ...string) error {
	p := "r"
	callerperm := cred.GetPerm().GetIntegration()
	base := Base.GetIntegration()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckUpdateIntegration(cred *auth.Credential, accid string, agids ...string) error {
	p := "u"
	callerperm := cred.GetPerm().GetIntegration()
	base := Base.GetIntegration()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckDeleteIntegration(cred *auth.Credential, accid string, agids ...string) error {
	p := "d"
	callerperm := cred.GetPerm().GetIntegration()
	base := Base.GetIntegration()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckCreateCannedResponse(cred *auth.Credential, accid string, agids ...string) error {
	p := "c"
	callerperm := cred.GetPerm().GetCannedResponse()
	base := Base.GetCannedResponse()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckReadCannedResponse(cred *auth.Credential, accid string, agids ...string) error {
	p := "r"
	callerperm := cred.GetPerm().GetCannedResponse()
	base := Base.GetCannedResponse()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckUpdateCannedResponse(cred *auth.Credential, accid string, agids ...string) error {
	p := "u"
	callerperm := cred.GetPerm().GetCannedResponse()
	base := Base.GetCannedResponse()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckDeleteCannedResponse(cred *auth.Credential, accid string, agids ...string) error {
	p := "d"
	callerperm := cred.GetPerm().GetCannedResponse()
	base := Base.GetCannedResponse()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckCreateTag(cred *auth.Credential, accid string, agids ...string) error {
	p := "c"
	callerperm := cred.GetPerm().GetTag()
	base := Base.GetTag()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckReadTag(cred *auth.Credential, accid string, agids ...string) error {
	p := "r"
	callerperm := cred.GetPerm().GetTag()
	base := Base.GetTag()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckUpdateTag(cred *auth.Credential, accid string, agids ...string) error {
	p := "u"
	callerperm := cred.GetPerm().GetTag()
	base := Base.GetTag()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckDeleteTag(cred *auth.Credential, accid string, agids ...string) error {
	p := "d"
	callerperm := cred.GetPerm().GetTag()
	base := Base.GetTag()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckCreateWhitelistIp(cred *auth.Credential, accid string, agids ...string) error {
	p := "c"
	callerperm := cred.GetPerm().GetWhitelistIp()
	base := Base.GetWhitelistIp()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckReadWhitelistIp(cred *auth.Credential, accid string, agids ...string) error {
	p := "r"
	callerperm := cred.GetPerm().GetWhitelistIp()
	base := Base.GetWhitelistIp()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckUpdateWhitelistIp(cred *auth.Credential, accid string, agids ...string) error {
	p := "u"
	callerperm := cred.GetPerm().GetWhitelistIp()
	base := Base.GetWhitelistIp()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckDeleteWhitelistIp(cred *auth.Credential, accid string, agids ...string) error {
	p := "d"
	callerperm := cred.GetPerm().GetWhitelistIp()
	base := Base.GetWhitelistIp()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckCreateWhitelistUser(cred *auth.Credential, accid string, agids ...string) error {
	p := "c"
	callerperm := cred.GetPerm().GetWhitelistUser()
	base := Base.GetWhitelistUser()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckReadWhitelistUser(cred *auth.Credential, accid string, agids ...string) error {
	p := "r"
	callerperm := cred.GetPerm().GetWhitelistUser()
	base := Base.GetWhitelistUser()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckUpdateWhitelistUser(cred *auth.Credential, accid string, agids ...string) error {
	p := "u"
	callerperm := cred.GetPerm().GetWhitelistUser()
	base := Base.GetWhitelistUser()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckDeleteWhitelistUser(cred *auth.Credential, accid string, agids ...string) error {
	p := "d"
	callerperm := cred.GetPerm().GetWhitelistUser()
	base := Base.GetWhitelistUser()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckCreateWhitelistDomain(cred *auth.Credential, accid string, agids ...string) error {
	p := "c"
	callerperm := cred.GetPerm().GetWhitelistDomain()
	base := Base.GetWhitelistDomain()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckReadWhitelistDomain(cred *auth.Credential, accid string, agids ...string) error {
	p := "r"
	callerperm := cred.GetPerm().GetWhitelistDomain()
	base := Base.GetWhitelistDomain()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckUpdateWhitelistDomain(cred *auth.Credential, accid string, agids ...string) error {
	p := "u"
	callerperm := cred.GetPerm().GetWhitelistDomain()
	base := Base.GetWhitelistDomain()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckDeleteWhitelistDomain(cred *auth.Credential, accid string, agids ...string) error {
	p := "d"
	callerperm := cred.GetPerm().GetWhitelistDomain()
	base := Base.GetWhitelistDomain()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckCreateWidget(cred *auth.Credential, accid string, agids ...string) error {
	p := "c"
	callerperm := cred.GetPerm().GetWidget()
	base := Base.GetWidget()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckReadWidget(cred *auth.Credential, accid string, agids ...string) error {
	p := "r"
	callerperm := cred.GetPerm().GetWidget()
	base := Base.GetWidget()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckUpdateWidget(cred *auth.Credential, accid string, agids ...string) error {
	p := "u"
	callerperm := cred.GetPerm().GetWidget()
	base := Base.GetWidget()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckDeleteWidget(cred *auth.Credential, accid string, agids ...string) error {
	p := "d"
	callerperm := cred.GetPerm().GetWidget()
	base := Base.GetWidget()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckCreateSubscription(cred *auth.Credential, accid string, agids ...string) error {
	p := "c"
	callerperm := cred.GetPerm().GetSubscription()
	base := Base.GetSubscription()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckReadSubscription(cred *auth.Credential, accid string, agids ...string) error {
	p := "r"
	callerperm := cred.GetPerm().GetSubscription()
	base := Base.GetSubscription()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckUpdateSubscription(cred *auth.Credential, accid string, agids ...string) error {
	p := "u"
	callerperm := cred.GetPerm().GetSubscription()
	base := Base.GetSubscription()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckDeleteSubscription(cred *auth.Credential, accid string, agids ...string) error {
	p := "d"
	callerperm := cred.GetPerm().GetSubscription()
	base := Base.GetSubscription()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckCreateInvoice(cred *auth.Credential, accid string, agids ...string) error {
	p := "c"
	callerperm := cred.GetPerm().GetInvoice()
	base := Base.GetInvoice()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckReadInvoice(cred *auth.Credential, accid string, agids ...string) error {
	p := "r"
	callerperm := cred.GetPerm().GetInvoice()
	base := Base.GetInvoice()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckUpdateInvoice(cred *auth.Credential, accid string, agids ...string) error {
	p := "u"
	callerperm := cred.GetPerm().GetInvoice()
	base := Base.GetInvoice()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckDeleteInvoice(cred *auth.Credential, accid string, agids ...string) error {
	p := "d"
	callerperm := cred.GetPerm().GetInvoice()
	base := Base.GetInvoice()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckCreatePaymentMethod(cred *auth.Credential, accid string, agids ...string) error {
	p := "c"
	callerperm := cred.GetPerm().GetPaymentMethod()
	base := Base.GetPaymentMethod()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckReadPaymentMethod(cred *auth.Credential, accid string, agids ...string) error {
	p := "r"
	callerperm := cred.GetPerm().GetPaymentMethod()
	base := Base.GetPaymentMethod()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckUpdatePaymentMethod(cred *auth.Credential, accid string, agids ...string) error {
	p := "u"
	callerperm := cred.GetPerm().GetPaymentMethod()
	base := Base.GetPaymentMethod()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckDeletePaymentMethod(cred *auth.Credential, accid string, agids ...string) error {
	p := "d"
	callerperm := cred.GetPerm().GetPaymentMethod()
	base := Base.GetPaymentMethod()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckCreateBill(cred *auth.Credential, accid string, agids ...string) error {
	p := "c"
	callerperm := cred.GetPerm().GetBill()
	base := Base.GetBill()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckReadBill(cred *auth.Credential, accid string, agids ...string) error {
	p := "r"
	callerperm := cred.GetPerm().GetBill()
	base := Base.GetBill()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckUpdateBill(cred *auth.Credential, accid string, agids ...string) error {
	p := "u"
	callerperm := cred.GetPerm().GetBill()
	base := Base.GetBill()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckDeleteBill(cred *auth.Credential, accid string, agids ...string) error {
	p := "d"
	callerperm := cred.GetPerm().GetBill()
	base := Base.GetBill()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckCreatePaymentLog(cred *auth.Credential, accid string, agids ...string) error {
	p := "c"
	callerperm := cred.GetPerm().GetPaymentLog()
	base := Base.GetPaymentLog()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckReadPaymentLog(cred *auth.Credential, accid string, agids ...string) error {
	p := "r"
	callerperm := cred.GetPerm().GetPaymentLog()
	base := Base.GetPaymentLog()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckUpdatePaymentLog(cred *auth.Credential, accid string, agids ...string) error {
	p := "u"
	callerperm := cred.GetPerm().GetPaymentLog()
	base := Base.GetPaymentLog()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckDeletePaymentLog(cred *auth.Credential, accid string, agids ...string) error {
	p := "d"
	callerperm := cred.GetPerm().GetPaymentLog()
	base := Base.GetPaymentLog()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckCreatePaymentComment(cred *auth.Credential, accid string, agids ...string) error {
	p := "c"
	callerperm := cred.GetPerm().GetPaymentComment()
	base := Base.GetPaymentComment()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckReadPaymentComment(cred *auth.Credential, accid string, agids ...string) error {
	p := "r"
	callerperm := cred.GetPerm().GetPaymentComment()
	base := Base.GetPaymentComment()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckUpdatePaymentComment(cred *auth.Credential, accid string, agids ...string) error {
	p := "u"
	callerperm := cred.GetPerm().GetPaymentComment()
	base := Base.GetPaymentComment()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckDeletePaymentComment(cred *auth.Credential, accid string, agids ...string) error {
	p := "d"
	callerperm := cred.GetPerm().GetPaymentComment()
	base := Base.GetPaymentComment()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckCreateUser(cred *auth.Credential, accid string, agids ...string) error {
	p := "c"
	callerperm := cred.GetPerm().GetUser()
	base := Base.GetUser()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckReadUser(cred *auth.Credential, accid string, agids ...string) error {
	p := "r"
	callerperm := cred.GetPerm().GetUser()
	base := Base.GetUser()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckUpdateUser(cred *auth.Credential, accid string, agids ...string) error {
	p := "u"
	callerperm := cred.GetPerm().GetUser()
	base := Base.GetUser()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckDeleteUser(cred *auth.Credential, accid string, agids ...string) error {
	p := "d"
	callerperm := cred.GetPerm().GetUser()
	base := Base.GetUser()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckCreateAutomation(cred *auth.Credential, accid string, agids ...string) error {
	p := "c"
	callerperm := cred.GetPerm().GetAutomation()
	base := Base.GetAutomation()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckReadAutomation(cred *auth.Credential, accid string, agids ...string) error {
	p := "r"
	callerperm := cred.GetPerm().GetAutomation()
	base := Base.GetAutomation()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckUpdateAutomation(cred *auth.Credential, accid string, agids ...string) error {
	p := "u"
	callerperm := cred.GetPerm().GetAutomation()
	base := Base.GetAutomation()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckDeleteAutomation(cred *auth.Credential, accid string, agids ...string) error {
	p := "d"
	callerperm := cred.GetPerm().GetAutomation()
	base := Base.GetAutomation()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckCreatePing(cred *auth.Credential, accid string, agids ...string) error {
	p := "c"
	callerperm := cred.GetPerm().GetPing()
	base := Base.GetPing()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckReadPing(cred *auth.Credential, accid string, agids ...string) error {
	p := "r"
	callerperm := cred.GetPerm().GetPing()
	base := Base.GetPing()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckUpdatePing(cred *auth.Credential, accid string, agids ...string) error {
	p := "u"
	callerperm := cred.GetPerm().GetPing()
	base := Base.GetPing()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckDeletePing(cred *auth.Credential, accid string, agids ...string) error {
	p := "d"
	callerperm := cred.GetPerm().GetPing()
	base := Base.GetPing()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckCreateAttribute(cred *auth.Credential, accid string, agids ...string) error {
	p := "c"
	callerperm := cred.GetPerm().GetAttribute()
	base := Base.GetAttribute()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckReadAttribute(cred *auth.Credential, accid string, agids ...string) error {
	p := "r"
	callerperm := cred.GetPerm().GetAttribute()
	base := Base.GetAttribute()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckUpdateAttribute(cred *auth.Credential, accid string, agids ...string) error {
	p := "u"
	callerperm := cred.GetPerm().GetAttribute()
	base := Base.GetAttribute()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckDeleteAttribute(cred *auth.Credential, accid string, agids ...string) error {
	p := "d"
	callerperm := cred.GetPerm().GetAttribute()
	base := Base.GetAttribute()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckCreateAgentNotification(cred *auth.Credential, accid string, agids ...string) error {
	p := "c"
	callerperm := cred.GetPerm().GetAgentNotification()
	base := Base.GetAgentNotification()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckReadAgentNotification(cred *auth.Credential, accid string, agids ...string) error {
	p := "r"
	callerperm := cred.GetPerm().GetAgentNotification()
	base := Base.GetAgentNotification()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckUpdateAgentNotification(cred *auth.Credential, accid string, agids ...string) error {
	p := "u"
	callerperm := cred.GetPerm().GetAgentNotification()
	base := Base.GetAgentNotification()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckDeleteAgentNotification(cred *auth.Credential, accid string, agids ...string) error {
	p := "d"
	callerperm := cred.GetPerm().GetAgentNotification()
	base := Base.GetAgentNotification()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckCreateConversationExport(cred *auth.Credential, accid string, agids ...string) error {
	p := "c"
	callerperm := cred.GetPerm().GetConversationExport()
	base := Base.GetConversationExport()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckReadConversationExport(cred *auth.Credential, accid string, agids ...string) error {
	p := "r"
	callerperm := cred.GetPerm().GetConversationExport()
	base := Base.GetConversationExport()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckUpdateConversationExport(cred *auth.Credential, accid string, agids ...string) error {
	p := "u"
	callerperm := cred.GetPerm().GetConversationExport()
	base := Base.GetConversationExport()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckDeleteConversationExport(cred *auth.Credential, accid string, agids ...string) error {
	p := "d"
	callerperm := cred.GetPerm().GetConversationExport()
	base := Base.GetConversationExport()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckCreateConversationReport(cred *auth.Credential, accid string, agids ...string) error {
	p := "c"
	callerperm := cred.GetPerm().GetConversationReport()
	base := Base.GetConversationReport()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckReadConversationReport(cred *auth.Credential, accid string, agids ...string) error {
	p := "r"
	callerperm := cred.GetPerm().GetConversationReport()
	base := Base.GetConversationReport()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckUpdateConversationReport(cred *auth.Credential, accid string, agids ...string) error {
	p := "u"
	callerperm := cred.GetPerm().GetConversationReport()
	base := Base.GetConversationReport()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckDeleteConversationReport(cred *auth.Credential, accid string, agids ...string) error {
	p := "d"
	callerperm := cred.GetPerm().GetConversationReport()
	base := Base.GetConversationReport()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckCreateContent(cred *auth.Credential, accid string, agids ...string) error {
	p := "c"
	callerperm := cred.GetPerm().GetContent()
	base := Base.GetContent()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckReadContent(cred *auth.Credential, accid string, agids ...string) error {
	p := "r"
	callerperm := cred.GetPerm().GetContent()
	base := Base.GetContent()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckUpdateContent(cred *auth.Credential, accid string, agids ...string) error {
	p := "u"
	callerperm := cred.GetPerm().GetContent()
	base := Base.GetContent()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckDeleteContent(cred *auth.Credential, accid string, agids ...string) error {
	p := "d"
	callerperm := cred.GetPerm().GetContent()
	base := Base.GetContent()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckCreatePipeline(cred *auth.Credential, accid string, agids ...string) error {
	p := "c"
	callerperm := cred.GetPerm().GetPipeline()
	base := Base.GetPipeline()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckReadPipeline(cred *auth.Credential, accid string, agids ...string) error {
	p := "r"
	callerperm := cred.GetPerm().GetPipeline()
	base := Base.GetPipeline()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckUpdatePipeline(cred *auth.Credential, accid string, agids ...string) error {
	p := "u"
	callerperm := cred.GetPerm().GetPipeline()
	base := Base.GetPipeline()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckDeletePipeline(cred *auth.Credential, accid string, agids ...string) error {
	p := "d"
	callerperm := cred.GetPerm().GetPipeline()
	base := Base.GetPipeline()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckCreateCurrency(cred *auth.Credential, accid string, agids ...string) error {
	p := "c"
	callerperm := cred.GetPerm().GetCurrency()
	base := Base.GetCurrency()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckReadCurrency(cred *auth.Credential, accid string, agids ...string) error {
	p := "r"
	callerperm := cred.GetPerm().GetCurrency()
	base := Base.GetCurrency()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckUpdateCurrency(cred *auth.Credential, accid string, agids ...string) error {
	p := "u"
	callerperm := cred.GetPerm().GetCurrency()
	base := Base.GetCurrency()
	return C2(p, base, callerperm, cred, accid, agids...)
}

func CheckDeleteCurrency(cred *auth.Credential, accid string, agids ...string) error {
	p := "d"
	callerperm := cred.GetPerm().GetCurrency()
	base := Base.GetCurrency()
	return C2(p, base, callerperm, cred, accid, agids...)
}
