// Code generated by "perm_generator -file vendor/github.com/subiz/header/auth/auth.pb.go -type Permission"; DO NOT EDIT.

package perm

import "github.com/subiz/header/auth"

func contains(s string, ss []string) bool {
	for _, i := range ss {
		if i == s {
			return true
		}
	}
	return false
}

var CREATEPERM = strPermToInt("c")
var READPERM = strPermToInt("r")
var UPDATEPERM = strPermToInt("u")
var DELETEPERM = strPermToInt("d")

func CheckCreateAccount(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetAccount()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(CREATEPERM, callerperm, ismine, isaccount)
}

func CheckReadAccount(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetAccount()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(READPERM, callerperm, ismine, isaccount)
}

func CheckUpdateAccount(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetAccount()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(UPDATEPERM, callerperm, ismine, isaccount)
}

func CheckDeleteAccount(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetAccount()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(DELETEPERM, callerperm, ismine, isaccount)
}
func CheckCreateAgent(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetAgent()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(CREATEPERM, callerperm, ismine, isaccount)
}

func CheckReadAgent(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetAgent()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(READPERM, callerperm, ismine, isaccount)
}

func CheckUpdateAgent(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetAgent()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(UPDATEPERM, callerperm, ismine, isaccount)
}

func CheckDeleteAgent(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetAgent()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(DELETEPERM, callerperm, ismine, isaccount)
}
func CheckCreateAgentPassword(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetAgentPassword()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(CREATEPERM, callerperm, ismine, isaccount)
}

func CheckReadAgentPassword(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetAgentPassword()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(READPERM, callerperm, ismine, isaccount)
}

func CheckUpdateAgentPassword(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetAgentPassword()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(UPDATEPERM, callerperm, ismine, isaccount)
}

func CheckDeleteAgentPassword(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetAgentPassword()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(DELETEPERM, callerperm, ismine, isaccount)
}
func CheckCreatePermission(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetPermission()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(CREATEPERM, callerperm, ismine, isaccount)
}

func CheckReadPermission(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetPermission()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(READPERM, callerperm, ismine, isaccount)
}

func CheckUpdatePermission(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetPermission()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(UPDATEPERM, callerperm, ismine, isaccount)
}

func CheckDeletePermission(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetPermission()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(DELETEPERM, callerperm, ismine, isaccount)
}
func CheckCreateAgentGroup(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetAgentGroup()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(CREATEPERM, callerperm, ismine, isaccount)
}

func CheckReadAgentGroup(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetAgentGroup()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(READPERM, callerperm, ismine, isaccount)
}

func CheckUpdateAgentGroup(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetAgentGroup()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(UPDATEPERM, callerperm, ismine, isaccount)
}

func CheckDeleteAgentGroup(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetAgentGroup()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(DELETEPERM, callerperm, ismine, isaccount)
}
func CheckCreateSegmentation(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetSegmentation()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(CREATEPERM, callerperm, ismine, isaccount)
}

func CheckReadSegmentation(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetSegmentation()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(READPERM, callerperm, ismine, isaccount)
}

func CheckUpdateSegmentation(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetSegmentation()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(UPDATEPERM, callerperm, ismine, isaccount)
}

func CheckDeleteSegmentation(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetSegmentation()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(DELETEPERM, callerperm, ismine, isaccount)
}
func CheckCreateClient(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetClient()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(CREATEPERM, callerperm, ismine, isaccount)
}

func CheckReadClient(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetClient()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(READPERM, callerperm, ismine, isaccount)
}

func CheckUpdateClient(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetClient()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(UPDATEPERM, callerperm, ismine, isaccount)
}

func CheckDeleteClient(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetClient()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(DELETEPERM, callerperm, ismine, isaccount)
}
func CheckCreateRule(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetRule()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(CREATEPERM, callerperm, ismine, isaccount)
}

func CheckReadRule(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetRule()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(READPERM, callerperm, ismine, isaccount)
}

func CheckUpdateRule(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetRule()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(UPDATEPERM, callerperm, ismine, isaccount)
}

func CheckDeleteRule(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetRule()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(DELETEPERM, callerperm, ismine, isaccount)
}
func CheckCreateConversation(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetConversation()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(CREATEPERM, callerperm, ismine, isaccount)
}

func CheckReadConversation(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetConversation()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(READPERM, callerperm, ismine, isaccount)
}

func CheckUpdateConversation(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetConversation()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(UPDATEPERM, callerperm, ismine, isaccount)
}

func CheckDeleteConversation(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetConversation()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(DELETEPERM, callerperm, ismine, isaccount)
}
func CheckCreateIntegration(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetIntegration()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(CREATEPERM, callerperm, ismine, isaccount)
}

func CheckReadIntegration(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetIntegration()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(READPERM, callerperm, ismine, isaccount)
}

func CheckUpdateIntegration(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetIntegration()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(UPDATEPERM, callerperm, ismine, isaccount)
}

func CheckDeleteIntegration(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetIntegration()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(DELETEPERM, callerperm, ismine, isaccount)
}
func CheckCreateCannedResponse(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetCannedResponse()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(CREATEPERM, callerperm, ismine, isaccount)
}

func CheckReadCannedResponse(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetCannedResponse()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(READPERM, callerperm, ismine, isaccount)
}

func CheckUpdateCannedResponse(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetCannedResponse()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(UPDATEPERM, callerperm, ismine, isaccount)
}

func CheckDeleteCannedResponse(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetCannedResponse()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(DELETEPERM, callerperm, ismine, isaccount)
}
func CheckCreateTag(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetTag()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(CREATEPERM, callerperm, ismine, isaccount)
}

func CheckReadTag(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetTag()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(READPERM, callerperm, ismine, isaccount)
}

func CheckUpdateTag(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetTag()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(UPDATEPERM, callerperm, ismine, isaccount)
}

func CheckDeleteTag(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetTag()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(DELETEPERM, callerperm, ismine, isaccount)
}
func CheckCreateWhitelistIp(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetWhitelistIp()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(CREATEPERM, callerperm, ismine, isaccount)
}

func CheckReadWhitelistIp(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetWhitelistIp()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(READPERM, callerperm, ismine, isaccount)
}

func CheckUpdateWhitelistIp(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetWhitelistIp()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(UPDATEPERM, callerperm, ismine, isaccount)
}

func CheckDeleteWhitelistIp(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetWhitelistIp()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(DELETEPERM, callerperm, ismine, isaccount)
}
func CheckCreateWhitelistUser(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetWhitelistUser()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(CREATEPERM, callerperm, ismine, isaccount)
}

func CheckReadWhitelistUser(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetWhitelistUser()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(READPERM, callerperm, ismine, isaccount)
}

func CheckUpdateWhitelistUser(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetWhitelistUser()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(UPDATEPERM, callerperm, ismine, isaccount)
}

func CheckDeleteWhitelistUser(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetWhitelistUser()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(DELETEPERM, callerperm, ismine, isaccount)
}
func CheckCreateWhitelistDomain(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetWhitelistDomain()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(CREATEPERM, callerperm, ismine, isaccount)
}

func CheckReadWhitelistDomain(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetWhitelistDomain()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(READPERM, callerperm, ismine, isaccount)
}

func CheckUpdateWhitelistDomain(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetWhitelistDomain()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(UPDATEPERM, callerperm, ismine, isaccount)
}

func CheckDeleteWhitelistDomain(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetWhitelistDomain()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(DELETEPERM, callerperm, ismine, isaccount)
}
func CheckCreateWidget(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetWidget()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(CREATEPERM, callerperm, ismine, isaccount)
}

func CheckReadWidget(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetWidget()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(READPERM, callerperm, ismine, isaccount)
}

func CheckUpdateWidget(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetWidget()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(UPDATEPERM, callerperm, ismine, isaccount)
}

func CheckDeleteWidget(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetWidget()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(DELETEPERM, callerperm, ismine, isaccount)
}
func CheckCreateSubscription(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetSubscription()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(CREATEPERM, callerperm, ismine, isaccount)
}

func CheckReadSubscription(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetSubscription()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(READPERM, callerperm, ismine, isaccount)
}

func CheckUpdateSubscription(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetSubscription()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(UPDATEPERM, callerperm, ismine, isaccount)
}

func CheckDeleteSubscription(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetSubscription()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(DELETEPERM, callerperm, ismine, isaccount)
}
func CheckCreateInvoice(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetInvoice()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(CREATEPERM, callerperm, ismine, isaccount)
}

func CheckReadInvoice(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetInvoice()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(READPERM, callerperm, ismine, isaccount)
}

func CheckUpdateInvoice(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetInvoice()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(UPDATEPERM, callerperm, ismine, isaccount)
}

func CheckDeleteInvoice(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetInvoice()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(DELETEPERM, callerperm, ismine, isaccount)
}
func CheckCreatePaymentMethod(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetPaymentMethod()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(CREATEPERM, callerperm, ismine, isaccount)
}

func CheckReadPaymentMethod(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetPaymentMethod()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(READPERM, callerperm, ismine, isaccount)
}

func CheckUpdatePaymentMethod(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetPaymentMethod()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(UPDATEPERM, callerperm, ismine, isaccount)
}

func CheckDeletePaymentMethod(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetPaymentMethod()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(DELETEPERM, callerperm, ismine, isaccount)
}
func CheckCreateBill(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetBill()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(CREATEPERM, callerperm, ismine, isaccount)
}

func CheckReadBill(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetBill()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(READPERM, callerperm, ismine, isaccount)
}

func CheckUpdateBill(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetBill()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(UPDATEPERM, callerperm, ismine, isaccount)
}

func CheckDeleteBill(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetBill()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(DELETEPERM, callerperm, ismine, isaccount)
}
func CheckCreatePaymentLog(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetPaymentLog()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(CREATEPERM, callerperm, ismine, isaccount)
}

func CheckReadPaymentLog(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetPaymentLog()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(READPERM, callerperm, ismine, isaccount)
}

func CheckUpdatePaymentLog(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetPaymentLog()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(UPDATEPERM, callerperm, ismine, isaccount)
}

func CheckDeletePaymentLog(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetPaymentLog()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(DELETEPERM, callerperm, ismine, isaccount)
}
func CheckCreatePaymentComment(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetPaymentComment()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(CREATEPERM, callerperm, ismine, isaccount)
}

func CheckReadPaymentComment(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetPaymentComment()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(READPERM, callerperm, ismine, isaccount)
}

func CheckUpdatePaymentComment(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetPaymentComment()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(UPDATEPERM, callerperm, ismine, isaccount)
}

func CheckDeletePaymentComment(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetPaymentComment()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(DELETEPERM, callerperm, ismine, isaccount)
}
func CheckCreateUser(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetUser()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(CREATEPERM, callerperm, ismine, isaccount)
}

func CheckReadUser(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetUser()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(READPERM, callerperm, ismine, isaccount)
}

func CheckUpdateUser(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetUser()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(UPDATEPERM, callerperm, ismine, isaccount)
}

func CheckDeleteUser(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetUser()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(DELETEPERM, callerperm, ismine, isaccount)
}
func CheckCreateAutomation(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetAutomation()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(CREATEPERM, callerperm, ismine, isaccount)
}

func CheckReadAutomation(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetAutomation()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(READPERM, callerperm, ismine, isaccount)
}

func CheckUpdateAutomation(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetAutomation()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(UPDATEPERM, callerperm, ismine, isaccount)
}

func CheckDeleteAutomation(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetAutomation()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(DELETEPERM, callerperm, ismine, isaccount)
}
func CheckCreatePing(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetPing()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(CREATEPERM, callerperm, ismine, isaccount)
}

func CheckReadPing(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetPing()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(READPERM, callerperm, ismine, isaccount)
}

func CheckUpdatePing(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetPing()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(UPDATEPERM, callerperm, ismine, isaccount)
}

func CheckDeletePing(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetPing()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(DELETEPERM, callerperm, ismine, isaccount)
}
func CheckCreateAttribute(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetAttribute()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(CREATEPERM, callerperm, ismine, isaccount)
}

func CheckReadAttribute(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetAttribute()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(READPERM, callerperm, ismine, isaccount)
}

func CheckUpdateAttribute(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetAttribute()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(UPDATEPERM, callerperm, ismine, isaccount)
}

func CheckDeleteAttribute(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetAttribute()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(DELETEPERM, callerperm, ismine, isaccount)
}
func CheckCreateAgentNotification(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetAgentNotification()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(CREATEPERM, callerperm, ismine, isaccount)
}

func CheckReadAgentNotification(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetAgentNotification()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(READPERM, callerperm, ismine, isaccount)
}

func CheckUpdateAgentNotification(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetAgentNotification()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(UPDATEPERM, callerperm, ismine, isaccount)
}

func CheckDeleteAgentNotification(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetAgentNotification()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(DELETEPERM, callerperm, ismine, isaccount)
}
func CheckCreateConversationExport(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetConversationExport()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(CREATEPERM, callerperm, ismine, isaccount)
}

func CheckReadConversationExport(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetConversationExport()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(READPERM, callerperm, ismine, isaccount)
}

func CheckUpdateConversationExport(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetConversationExport()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(UPDATEPERM, callerperm, ismine, isaccount)
}

func CheckDeleteConversationExport(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetConversationExport()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(DELETEPERM, callerperm, ismine, isaccount)
}
func CheckCreateConversationReport(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetConversationReport()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(CREATEPERM, callerperm, ismine, isaccount)
}

func CheckReadConversationReport(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetConversationReport()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(READPERM, callerperm, ismine, isaccount)
}

func CheckUpdateConversationReport(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetConversationReport()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(UPDATEPERM, callerperm, ismine, isaccount)
}

func CheckDeleteConversationReport(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetConversationReport()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(DELETEPERM, callerperm, ismine, isaccount)
}
func CheckCreateContent(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetContent()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(CREATEPERM, callerperm, ismine, isaccount)
}

func CheckReadContent(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetContent()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(READPERM, callerperm, ismine, isaccount)
}

func CheckUpdateContent(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetContent()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(UPDATEPERM, callerperm, ismine, isaccount)
}

func CheckDeleteContent(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetContent()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(DELETEPERM, callerperm, ismine, isaccount)
}
func CheckCreatePipeline(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetPipeline()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(CREATEPERM, callerperm, ismine, isaccount)
}

func CheckReadPipeline(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetPipeline()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(READPERM, callerperm, ismine, isaccount)
}

func CheckUpdatePipeline(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetPipeline()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(UPDATEPERM, callerperm, ismine, isaccount)
}

func CheckDeletePipeline(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetPipeline()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(DELETEPERM, callerperm, ismine, isaccount)
}
func CheckCreateCurrency(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetCurrency()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(CREATEPERM, callerperm, ismine, isaccount)
}

func CheckReadCurrency(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetCurrency()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(READPERM, callerperm, ismine, isaccount)
}

func CheckUpdateCurrency(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetCurrency()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(UPDATEPERM, callerperm, ismine, isaccount)
}

func CheckDeleteCurrency(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetCurrency()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(DELETEPERM, callerperm, ismine, isaccount)
}
func CheckCreateServiceLevelAgreement(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetServiceLevelAgreement()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(CREATEPERM, callerperm, ismine, isaccount)
}

func CheckReadServiceLevelAgreement(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetServiceLevelAgreement()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(READPERM, callerperm, ismine, isaccount)
}

func CheckUpdateServiceLevelAgreement(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetServiceLevelAgreement()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(UPDATEPERM, callerperm, ismine, isaccount)
}

func CheckDeleteServiceLevelAgreement(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetServiceLevelAgreement()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(DELETEPERM, callerperm, ismine, isaccount)
}
func CheckCreateMessageTemplate(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetMessageTemplate()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(CREATEPERM, callerperm, ismine, isaccount)
}

func CheckReadMessageTemplate(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetMessageTemplate()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(READPERM, callerperm, ismine, isaccount)
}

func CheckUpdateMessageTemplate(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetMessageTemplate()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(UPDATEPERM, callerperm, ismine, isaccount)
}

func CheckDeleteMessageTemplate(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetMessageTemplate()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(DELETEPERM, callerperm, ismine, isaccount)
}
func CheckCreateAgentPresence(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetAgentPresence()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(CREATEPERM, callerperm, ismine, isaccount)
}

func CheckReadAgentPresence(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetAgentPresence()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(READPERM, callerperm, ismine, isaccount)
}

func CheckUpdateAgentPresence(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetAgentPresence()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(UPDATEPERM, callerperm, ismine, isaccount)
}

func CheckDeleteAgentPresence(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetAgentPresence()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(DELETEPERM, callerperm, ismine, isaccount)
}
func CheckCreateAgentPreference(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetAgentPreference()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(CREATEPERM, callerperm, ismine, isaccount)
}

func CheckReadAgentPreference(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetAgentPreference()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(READPERM, callerperm, ismine, isaccount)
}

func CheckUpdateAgentPreference(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetAgentPreference()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(UPDATEPERM, callerperm, ismine, isaccount)
}

func CheckDeleteAgentPreference(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetAgentPreference()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(DELETEPERM, callerperm, ismine, isaccount)
}
func CheckCreatePromotionCode(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetPromotionCode()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(CREATEPERM, callerperm, ismine, isaccount)
}

func CheckReadPromotionCode(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetPromotionCode()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(READPERM, callerperm, ismine, isaccount)
}

func CheckUpdatePromotionCode(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetPromotionCode()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(UPDATEPERM, callerperm, ismine, isaccount)
}

func CheckDeletePromotionCode(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetPromotionCode()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(DELETEPERM, callerperm, ismine, isaccount)
}
func CheckCreateReferral(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetReferral()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(CREATEPERM, callerperm, ismine, isaccount)
}

func CheckReadReferral(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetReferral()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(READPERM, callerperm, ismine, isaccount)
}

func CheckUpdateReferral(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetReferral()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(UPDATEPERM, callerperm, ismine, isaccount)
}

func CheckDeleteReferral(cred *auth.Credential, accid string, agids ...string) error {
	callerperm := cred.GetPerm().GetReferral()
	ismine := cred.GetAccountId() == accid && contains(cred.GetIssuer(), agids)
	isaccount := cred.GetAccountId() == accid
	return checkPerm(DELETEPERM, callerperm, ismine, isaccount)
}

func pInt32(i int32) *int32 {
	return &i
}

// IntersectPermission finds the intersection of permission a and permission b
func IntersectPermission(a, b *auth.Permission) *auth.Permission {
	if a == nil {
		a = &auth.Permission{}
	}

	if b == nil {
		b = &auth.Permission{}
	}

	return &auth.Permission{
		Account:               a.GetAccount() & b.GetAccount(),
		Agent:                 a.GetAgent() & b.GetAgent(),
		AgentPassword:         a.GetAgentPassword() & b.GetAgentPassword(),
		Permission:            a.GetPermission() & b.GetPermission(),
		AgentGroup:            a.GetAgentGroup() & b.GetAgentGroup(),
		Segmentation:          a.GetSegmentation() & b.GetSegmentation(),
		Client:                a.GetClient() & b.GetClient(),
		Rule:                  a.GetRule() & b.GetRule(),
		Conversation:          a.GetConversation() & b.GetConversation(),
		Integration:           a.GetIntegration() & b.GetIntegration(),
		CannedResponse:        a.GetCannedResponse() & b.GetCannedResponse(),
		Tag:                   a.GetTag() & b.GetTag(),
		WhitelistIp:           a.GetWhitelistIp() & b.GetWhitelistIp(),
		WhitelistUser:         a.GetWhitelistUser() & b.GetWhitelistUser(),
		WhitelistDomain:       a.GetWhitelistDomain() & b.GetWhitelistDomain(),
		Widget:                a.GetWidget() & b.GetWidget(),
		Subscription:          a.GetSubscription() & b.GetSubscription(),
		Invoice:               a.GetInvoice() & b.GetInvoice(),
		PaymentMethod:         a.GetPaymentMethod() & b.GetPaymentMethod(),
		Bill:                  a.GetBill() & b.GetBill(),
		PaymentLog:            a.GetPaymentLog() & b.GetPaymentLog(),
		PaymentComment:        a.GetPaymentComment() & b.GetPaymentComment(),
		User:                  a.GetUser() & b.GetUser(),
		Automation:            a.GetAutomation() & b.GetAutomation(),
		Ping:                  a.GetPing() & b.GetPing(),
		Attribute:             a.GetAttribute() & b.GetAttribute(),
		AgentNotification:     a.GetAgentNotification() & b.GetAgentNotification(),
		ConversationExport:    a.GetConversationExport() & b.GetConversationExport(),
		ConversationReport:    a.GetConversationReport() & b.GetConversationReport(),
		Content:               a.GetContent() & b.GetContent(),
		Pipeline:              a.GetPipeline() & b.GetPipeline(),
		Currency:              a.GetCurrency() & b.GetCurrency(),
		ServiceLevelAgreement: a.GetServiceLevelAgreement() & b.GetServiceLevelAgreement(),
		MessageTemplate:       a.GetMessageTemplate() & b.GetMessageTemplate(),
		AgentPresence:         a.GetAgentPresence() & b.GetAgentPresence(),
		AgentPreference:       a.GetAgentPreference() & b.GetAgentPreference(),
		PromotionCode:         a.GetPromotionCode() & b.GetPromotionCode(),
		Referral:              a.GetReferral() & b.GetReferral(),
	}
}
